### ISSUE TITLE
VS2015 Update 1 causes an error - Identifier Expected

### ISSUE THREAD

**Issue by MatthewSteeples** [T4MVC/T4MVC#54] opened 2015-12-01 18:24 UTC
I'm still investigating this but thought I'd post it here in case anyone else experiences the same thing. Just upgraded to 3.16.5 and we're getting the following code appear in the autogenerated T4MVC.cs file:

```
public override void ExecuteResult(System.Web.Mvc.ControllerContext ) { }
```

It appears in the `T4MVC_System_Web_Mvc_ActionResult` class. There's a similar missing parameter name in the `T4MVC_System_Web_Mvc_FileResult` class too.

Not been able to find any changes that cause this yet though

**Comment by MatthewSteeples** [comment] 2015-12-01 18:33
Small update, it would appear that it's not a 3.16.5 issue, but rather a VS2015 Update 1 issue. I rolled us back to 3.16.4 and the same issue appears. I'm afraid I'm not sure how to go about trying to get it debugged in VS

**Comment by fetters5** [comment] 2015-12-01 18:37
I can confirm that the same thing happened to me (and my coworker) after moving to  VS2015 Update 1

**Comment by MatthewSteeples** [comment] 2015-12-01 18:45
I would guess that the issue is with the `<#method.WriteFormalParameters(true); #>` piece on (or near) line 124

**Comment by davidebbo** [comment] 2015-12-01 19:31
That sucks if Update 1 regressed something. I'm on vacation this week and won't be able to help much. Please try to isolate exactly what behavior change caused this, and if we can work around. We may also need to report it to VS team. Thanks!

**Comment by AdrianLogan** [comment] 2015-12-01 20:19
The problem is that the Name parameter is empty for System.Web.Mvc.ControllerContext. And it is only a problem with Update 1 installed on VS 2015.

I dumped the output of the parameter below.
Microsoft.VisualStudio.TextTemplatingD95247332E89929EE0722A8E181018BC103218A8A2639F905A464534635131E74E76191C91B7D9A5AAC37C872CE5F4185CF5EBD213934C134D488E34F416C86A.GeneratedTextTransformation.MethodParamInfo}
    DefaultValue: null
    Name: ""
    RouteNameExpression: "\"\""
    Type: "System.Web.Mvc.ControllerContext"

As a temporary fix so that we could get working again I added a check to WriteFormalParameters to check for a empty name and type of System.Web.Mvc.ControllerContext - and then set the name to context (would it used to be)

**Comment by tim-elvidge** [comment] 2015-12-01 20:28
Hi Adrian, Could you post the code you used to resolve the issue.

**Comment by AdrianLogan** [comment] 2015-12-01 20:49
Okay but consider this a temporary hack.
On line 2030 you will have the WriteFormalParameters method. Replace that with the below:

```
public void WriteFormalParameters(bool first, bool includeDefaults = false)
{
    foreach (var p in Parameters)
    {
        if (first)
            first = false;
        else
            TT.Write(", ");

       var parameterName = p.Name;
       if (string.IsNullOrWhiteSpace(parameterName) &&
            p.Type == "System.Web.Mvc.ControllerContext") 
            parameterName = "context";

        TT.Write(p.Type + " " + parameterName );
        if(includeDefaults && !string.IsNullOrEmpty(p.DefaultValue))
            TT.Write(" = " + p.DefaultValue);
    }
}
```

**Comment by tim-elvidge** [comment] 2015-12-01 21:06
Thanks Adrian and Matthew, another bug I have discovered is where ActionParamsClass around lines 323 again the param.Name is empty. Having a go a working out a fix.

**Comment by MatthewSteeples** [comment] 2015-12-01 21:07
I've created a PR for it on the off-chance it doesn't end up being a short term fix (eg Update 2).

@tim-elvidge if you want to let me know the change for that I can update the PR so that there's only one change to put in

**Comment by pergardebrink** [comment] 2015-12-01 22:35
We had the same problem after Update 1 and I filed a bug with microsoft connect: https://connect.microsoft.com/VisualStudio/feedback/details/2080749/codeparameter2-in-text-templating-has-no-value-for-name-after-update-1

**Comment by tim-elvidge** [comment] 2015-12-01 22:42
Thanks Per, voted it up on Connect and confirmed a me too on this as well

**Comment by daveaglick** [comment] 2015-12-02 20:45
I can confirm the same problem. Voted on Connect as well.

**Comment by dbuenor** [comment] 2015-12-03 12:14
Same problem here. Thx for the fix @MatthewSteeples

**Comment by davidebbo** [comment] 2015-12-03 18:39
I'm going to try to track someone who works in this area to see if we can get their attention.

**Comment by davidebbo** [comment] 2015-12-03 20:14
Ok, I got news that someone is actively looking at it, so it should be in good hands.

**Comment by daveaglick** [comment] 2015-12-03 20:17
:+1:

Now get back to that vacation thing!

**Comment by davidebbo** [comment] 2015-12-03 20:27
I just ate a grapefruit off the tree, so I'm doing a bit of the vacation thing on the side ;)

Ok, now we have a tracking bug in Roslyn land: https://github.com/dotnet/roslyn/issues/7210

**Comment by subgurim** [comment] 2015-12-04 14:46
I know I'm late, just to confirm, I have the same problem and have the same conclusions.

Seems that the problem happens when working with Controllers with a custom parent controller (even if it's abstract)

**Comment by tim-elvidge** [comment] 2015-12-05 02:34
Ok the bug in Roslyn land: https://github.com/dotnet/roslyn/issues/7210 has now been closed with Resolution-Fixed. How long till us developers can use this fix?? 

I am coping with this using a check in code from Update 1 machine, pull down code from RTM VS2015, run T4MVC, check in, pull code back to Update 1 machine - compile etc.

Anyone else got a better work-around??

**Comment by davidebbo** [comment] 2015-12-05 05:54
I was given a test build of the fix and was able to verify that it corrects the problem. I did not get any info yet about when/how they will release it.

**Comment by NetTecture** [comment] 2015-12-08 18:50
Damn, that is a deal breaker here. Can I assume I have to stop all work on T4MVC utilizing web code until someone at MS releases a fix, likely in some months as Update 2?

**Comment by davidebbo** [comment] 2015-12-08 18:52
From what I heard, they're going to release a targeted fix much sooner than that, like maybe next week. So hopefully this issue will just go away soon.

**Comment by waynebrantley** [comment] 2015-12-08 19:04
@NetTecture the temporary hotfix above is working for us until they do release.

**Comment by leniel** [comment] 2015-12-10 17:18
:+1:

**Comment by davidebbo** [comment] 2015-12-15 17:58
Good news, the fix it out! https://msdn.microsoft.com/en-US/library/mt634751(VS.140).aspx

**Closed as completed by davidebbo** 2015-12-15 17:58 UTC

**Comment by subgurim** [comment] 2015-12-16 08:50
Great!! Works for me.

Thanks!

**Comment by sambruggeman** [comment] 2015-12-16 09:51
Fix works like a charm, thank you!

**Comment by sjmcallister** [comment] 2016-03-11 17:13
@davidebbo Could you add the link to the fix to the readme? I'm sure it would help people out right away instead of looking through issues.  Thanks!

**Comment by kevinkuszyk** [comment] 2016-03-11 17:21
@sjmcallister feel free to make that change on a PR and @davidebbo or I will merge it.
